[DEFAULT]
debian-branch = debian/master
debian-tag = debian/%(version)s
upstream-branch = upstream/latest
upstream-tag = upstream/%(version)s
upstream-vcs-tag=v%(version)s

[buildpackage]
submodules = True

[tag]
sign-tags = true

[export-orig]
submodules = true
