[DEFAULT]
debian-branch = debian/sid
debian-tag = debian/%(version)s
upstream-branch = upstream/latest
upstream-tag = v%(version)s

[buildpackage]
submodules = True

[tag]
sign-tags = true

[export-orig]
submodules = true
