usr/bin/phosh-session
usr/lib/systemd/user/gnome-session@phosh.target.d/session.conf
usr/lib/systemd/user/mobi.phosh.Shell.service
usr/lib/systemd/user/mobi.phosh.Shell.target
usr/libexec/phosh
usr/libexec/phosh-calendar-server
usr/libexec/phosh-searchd
usr/share/applications/mobi.phosh.Shell.desktop
usr/share/dbus-1/services/mobi.phosh.Shell.CalendarServer.service
usr/share/dbus-1/services/mobi.phosh.Shell.Search.service
usr/share/gnome-session/sessions/phosh.session
usr/share/icons/hicolor/symbolic/apps/mobi.phosh.Shell-symbolic.svg
usr/share/phosh/phoc.ini
usr/share/wayland-sessions/phosh.desktop
usr/share/xdg-desktop-portal/phosh-portals.conf
usr/share/xdg-desktop-portal/portals/phosh-shell.portal
usr/lib/systemd/user/mobi.phosh.OSK.target
usr/share/glib-2.0/schemas/mobi.phosh.shell.enums.xml
usr/share/glib-2.0/schemas/mobi.phosh.shell.gschema.xml
usr/share/locale

data/systemd/legacy/gnome-session-wayland.target /usr/share/phosh/systemd/
data/systemd/legacy/gnome-session-wayland@.target /usr/share/phosh/systemd/
